name: breath
on:
  push:
    branches:
      - "!master"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x
      - name: Build and test with Rake
        run: |
          sudo apt-get update -qq && sudo apt-get install -y apt-utils libsqlite3-dev
          gem install bundler
          bundle install --jobs 4 --retry 3 --without production development
          bundle exec rake db:migrate
          bundle exec rake
        env:
          RAILS_ENV: test
